### ISSUE TITLE
Shell config

### ISSUE THREAD

**Issue by marcbowes** [awslabs/amazon-qldb-shell#141]
As we approach the 2.0 release, we need to make sure the new shell config strategy is something we're happy with going forward. I think there are three broad questions:

1. Is the location and name right?
2. Is the format right?
3. Are the options right?

### Location

We're currently using the xdg crate but I'm not very happy with the outcome. Every single time I've tried to customize the config I can't remember the location! Here they are, for each platform:

- OSX: `~/Library/Application Support/qldbshell/default_config.toml`
- Linux: `~/.config/qldbshell/default_config.toml`
- Windows: `~\AppData\Local\qldbshell\default_config.toml`

I would personally prefer that the OSX and Linux paths were the same. There seems to be a split in the ecosystem around this idea. For example, fish shell uses `~/.config` regardless of OSX/Linux.

On the other hand, the crate we're using already supports `XDG_CONFIG_HOME` as an environment variable, so there is no real reason why the user couldn't change this themselves. I'm not sure there is value in us overriding the default here.

What I think it comes down to is it's really hard to know where to place the config file. Part of the problem is the CLI generator we're using only supports static strings in the help text, so if you run `qldb --help` you don't get a hint where to place the file:

```
qldb --help
< snip >
OPTIONS:
    -c, --config <config>
            Config file to load. By default, this file is in $XDG_CONFIG_HOME/qldbshell/default_config.toml

❯ echo $XDG_CONFIG_HOME
< nothing >
```

I think we should try fix that issue at least and just make peace with the XDG defaults on OSX being weird.

### Format

I think the main question here is whether we want TOML or Ion (text). When we started the 2.0 version it seemed like TOML made sense, but now I'm questing whether that was the right choice. Ion is pretty easy to write out by hand, and the reasons TOML has been useful (e.g. comments) can also be gained through Ion. Given QLDB users already need to know about Ion to use the system, it doesn't make sense to me to introduce another format unless there is some material benefit.

### Are the options right?

Is the structure and names what we want? I think so, but I've done 20 iterations on this now so I'm a little dizzy thinking it through. The current pattern is hierarchical which gives both DRY and convention over configuration.

**Comment by alpian** [comment]
Just my $0.02c (and I mean this, these are just opinions, but I think that's what you're asking for):

The config file format should be TOML. TOML is the least surprising format for a config file and looks a lot like git and other config files. Just because the transport happens to be Ion does not imply the config file format.

Just using myself as a reference, I had never heard of XDG. On OSX and Linux (and I agree with you they should be same) I would expect to find the config in `~/.config/qldbshell.toml`. The location on Windows seems right to me.

That addresses 1 and 2 -- will think a little more about 3.

**Comment by marcbowes** [comment]
Let's put a config file either side-by-side...

```toml
default_ledger = "shesellsrepls"

[[ledgers]]
name = "shesellsrepls"
region = "us-west-2"

[[ledgers]]
name = "vehicle-registration"
region = "us-east-1"

[ui]
edit_mode = "Emacs"
prompt = "$REGION:$LEDGER$ACTIVE_TRANSACTION> "
format = "table"

[debug]
log = "/tmp/qldb-shell.log"
```
```
{
    default_ledger: "shesellsrepls",
    ledgers: [
        {
            name: "shesellsrepls",
            region: "us-west-2",
        },
        {
            name: "vehicle-registration",
            region: "us-east-1",
        }        
    ],
    ui: {
        edit_mode: "Emacs",
        prompt: "$REGION:$LEDGER$ACTIVE_TRANSACTION> ",
        format: "table",
    }
    debug: {
        log: "/tmp/qldb-shell.log"        
    }
}
```

**Comment by marcbowes** [comment]
I think I prefer the Ion version tbh. 

I agree that simple TOML looks like unix conf files, and I like that. But because we have arrays and maps, it gets a little more complicated. I don't like the `[[ ]]` syntax in TOML, I find the JSON lists and maps syntax much clearer.

**Comment by marcbowes** [comment]
> Just my $0.02c (and I mean this, these are just opinions, but I think that's what you're asking for):

Provided those are US cents and not Canadian cents..

> Just because the transport happens to be Ion does not imply the config file format.

I'm maybe overthinking this, but I can imagine a future where the shell and webconsole can store settings inside the ledger itself.

**Comment by brack** [comment]
alright since i don't like pennies, i'm adding my .0000060 ETH: 

1) config location: i agree on defaulting to ~/.config or ~/.qldbshell or something like that. it looks like XDG convention would prefer defaulting to ~/.config/qldbshell. however, I am not sure I'm in favor of using XDG's macos default -- i think for a non-gui / cli-targeted application, it is much more intuitive to have the config alongside others. i also assume that QLDB customers in general, even if primary macos users, will often working from remote hosts without guis, so having things live in ~/.config would probably be less jarring when moving back and forth. i also found a similar, interesting discussion where someone dug into the Apple docs and found justification of why to avoid the XDG default for CLI-based applications, which I think I agree with: https://github.com/nushell/nushell/issues/893

2) Ion & TOML - I might be out of the loop a bit, but I'm not sure TOML is widely adopted across the various landscape of potential QLDB customers, I assume many will be most familiar with YAML, or, they won't really have a strong preference. Given that the config file (at the moment) is fairly straightforward in options, I don't know that format matters too much. However, given that we do want to reinforce Ion usage, I think it is worth being Ion-forward here as well. Plus, presumably, by the time a customer is using qldbshell, they've likely already ramped up to Ion and seeing Ion config won't be too jarring.

**Comment by marcbowes** [comment]
>     1. config location: i agree on defaulting to ~/.config or ~/.qldbshell or something like that. [..]

Ok, so it's not just me :). I'll make that change.

>     2. Ion & TOML - I might be out of the loop a bit, but I'm not sure TOML is widely adopted across the various landscape of potential QLDB customers, I assume many will be most familiar with YAML, or, they won't really have a strong preference. Given that the config file (at the moment) is fairly straightforward in options, I don't know that format matters too much. However, given that we do want to reinforce Ion usage, I think it is worth being Ion-forward here as well. Plus, presumably, by the time a customer is using qldbshell, they've likely already ramped up to Ion and seeing Ion config won't be too jarring.

Yeah and even though it's no big deal taking a dependency from a shell point of view (we don't require customers to install anything since it's a static binary), there is still *a dependency* in the sense customers have to understand it, have an editor that can read toml files (or, in Windows, associate an application to open it with).

I'm in favor of Ion. For most customers, they can just treat it like Json and it'll be fine. @alpian let me know if you want to veto..

>     3. release blocking - I'm not sure either would be release blocking, depending on how much marketing/messaging is happening. i'm not sure how much effort it is to address the above items, but, it seems fairly reasonable to update these after release, if it's as simple for customers as copy pasting the configs, or manually updating a few values in their new ion config based on their old toml config. overall though if we have general consensus on preferring ~/.config  and Ion, and it doesn't take much to change, i'd say it's worth doing prior to the initial 2.0 release

I think it's really hard to update later. Customers don't read or accurately follow release notes. They just expect it to keep working but be better. Investing in automated tools is hard as they have to remain in perpetuity and rollback is expected to work too.

**Comment by brack** [comment]
re 3: i see -- good point, especially about automated tools and backward compatibility. i don't think it would make sense to support both toml and ion config files either, in order to smooth that transition if we released with toml and added ion (assuming that would be feasible/possible)

**Comment by brack** [comment]
was doing a bit more reading on TOML vs YAML vs StrictYAML vs JSON etc etc. 

the most compelling sentiment i took away from a few posts was -- "everyone knows JSON." granted, we're talking about Ion, but given that it is a superset of JSON and we're already asking our customers to learn Ion, i figured it might be worth mentioning that Ion then might be less polarizing to the most general population of potential customers

**Comment by marcbowes** [comment]
I think what matters the most is clear configuration examples. Whether it's

```
[[ledgers]]
name = "foo"
```

or

```
ledgers: [
  {
    name: "foo"
  }
]
```

doesn't matter as much as showing customers an example.

**Comment by marcbowes** [comment]
> maybe the easiest way to close this out is to look at the Ion config and compare with the existing TOML config?

Already done that earlier in the thread, except without comments. TOML comments look like this:

```toml
[ui]
# tables are pretty
format = "table"
```

while Ion...

```ion
ui: {
  // tables are pretty
  format: "table"
}
```

**Comment by butleragrant** [comment]
I am leaning toward Ion. 

I know it is used elsewhere, but I personally haven't seen TOML used anywhere outside the Rust ecosystem. JSON on the other hand, is everywhere and I feel like Ion is "close enough" to JSON that customers will have no problem adapting. Also as was mentioned earlier, customers will want to learn Ion anyways.

**Comment by brack** [comment]
one last quick comment/nitpick -- if we're changing the config location/format, just figured i would also check on whether we should change the file name. right now it is default_config and i'm wondering if it should just be "config." the prefix "default_" leads me to believe maybe i should be creating a new config file / somehow overriding the default, rather than editing the default directly. it didn't look like that behavior exists, as it looks like the expectation is for the customer to directly edit the config file and override defaults within the default_config

i don't want to pile on too many changes here, but i figured i'd raise it as we're actively making changes here, and it's something difficult to change later

**Comment by marcbowes** [comment]
It's a good callout. The intention is to be able to do `--config-file PATH` in the future. Given that, do you still feel we should rename it? I'm fine either way. The days of needing to save on chars are behind us, so I like clear names.

**Comment by brack** [comment]
personally i would still probably prefer "config.ion" for the general case. i know people might want to relocate the config for personal preferences, if they don't have a traditional home directory, or if their if their home directory is just ephemeral. in that case, i think they'd be doing this with other tools as well and would know they are no longer using the default. i see your point though on the naming being very clear.

for me it starts to become unclear when making changes. it feels odd to me to change the defaults in the default config -- to say it a different way, if i make changes to the default config, it's no longer truly the default config, yet it is still named that way. i think at that point, the naming is no longer clear.

all that said, i'm also fine either way.

**Comment by guyilin-amazon** [comment]
Based on above discussion:
1. We have picked `Ion` as the Shell config file format
2. We want to change the config filename to `config.ion`
3. The config file path would be `~/.config/qldbshell/`  for both OSX and Linux

**Comment by marcbowes** [comment]
> for me it starts to become unclear when making changes. it feels odd to me to change the defaults in the default config -- to say it a different way, if i make changes to the default config, it's no longer truly the default config, yet it is still named that way. i think at that point, the naming is no longer clear.

This was very helpful for me, thanks. I see the confusion now. Just to spell it out..

For me, "default config" meant that if I ran `qldb` without any arguments then _my_ default config would be loaded, and it ought to contain a default ledger at a minimum. By way of contrast, `qldb --config PATH` would not use the _default_ config, rather it would load a _specific_ config.

I think the way you interpreted "default config" was that "the shell has some default config and you can edit it".

**Comment by brack** [comment]
@marcbowes thanks for elaborating. i see what you mean. i might be getting thrown off because i haven't personally seen other tools using anything other than just "config" so i might be trying to make something more out of the term "default" in the name.

**Comment by marcbowes** [comment]
Everything implemented as discussed.
