### ISSUE TITLE
Refine welcome message

### ISSUE THREAD

**Issue by guyilin-amazon** [awslabs/amazon-qldb-shell#148]
After starting the Shell, the current welcome message is:

```
Welcome to the Amazon QLDB Shell!

To start a transaction type 'start transaction', after which you may enter a series of PartiQL statements.
When your transaction is complete, enter 'commit' or 'abort' as appropriate.
```

Since the Shell enables the `auto_commit` mode by default, we could add info that we can execute statement directly without typing `begin` explicitly in `auto_commit` mode. Proposed new welcome message:

```
Welcome to Amazon QLDB Shell! 

In QLDB, everything is a transaction. By default, the auto_commit mode is enabled, so the shell will automatically perform transactions for you. 
If you want to perform a multi-statement transaction, you can type `start transaction` or `begin`, after which you may enter a series of PartiQL statements.
When your transaction is complete, enter 'commit' or 'abort' as appropriate.
```

We could also add PartiQL reference link in the welcome message as the same in the console help panel.

**Comment by brack** [comment]
Adding some context about the original discussion -- if I recall correctly, the original objective was to make sure that the transaction behavior is clear, since QLDB/shell behavior differs from others that customers will be familiar with. I'm also raising up a new point, which is to also briefly mention the PartiQL aspect, especially given that QLDB supports a subset.

I agree with Yilin that we may want to have some parity with what is in the console. 

In the meeting today we also discussed the proposal from the previous meeting not being entirely accurate.

With that in mind, and adding a bit about PartiQL, here's another proposal. It's a little long, but I also assume that once people get familiar with the console they'll turn off the welcome message if it's bothersome.

> Welcome to the QLDB shell!
> 
> \- Transactions: By default, the shell implicitly runs each statement in its own transaction and automatically commits the transaction if no errors are found. This is configurable. To start a multi-statement transaction, enter `begin`.
> \- PartiQL: a subset of PartiQL is supported, and elements returned by queries are in unordered "bags." For more details, check the shell guide in the developer guide.
> \- Developer Guide: https://docs.aws.amazon.com/qldb/latest/developerguide/data-shell.html
> \- Reminder: this welcome message can be disabled in the config.


(note: i pulled most of the transaction text from the [developer guide](http://mrbrto.aka.corp.amazon.com/qldbdocs/src/AWSLedgerApiDoc/build/server-root/qldb/latest/developerguide/data-shell.html#data-shell-indiv-statements))
