### ISSUE TITLE
Handle case when user inputs a non-existent ledger name

### ISSUE THREAD

**Issue by justing-bq** [awslabs/amazon-qldb-shell#34]
On rust, if the user runs the shell on a non-existent ledger, we get the following error:

% cargo run -- --ledger chess
warning: a method with this name may be added to the standard library in the future
   --> src/lib.rs:379:14
    |
379 |             .intersperse(",\n".to_owned())
    |              ^^^^^^^^^^^
    |
    = note: `#[warn(unstable_name_collisions)]` on by default
    = warning: once this method is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `itertools::Itertools::intersperse(...)` to keep using the current method

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/qldb --ledger chess`
Welcome to the Amazon QLDB Shell!

To start a transaction type '\start transaction', after which you may enter a series of PartiQL statements.
When your transaction is complete, enter '\commit' or '\abort' as appropriate.
qldb> start transaction
qldb *> CREATE TABLE TestTable
thread 'main' panicked at 'internal error: entered unreachable code', /Users/justingossett/Documents/dev/awslabs/amazon-qldb-shell/src/lib.rs:373:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by marcbowes** [comment]
Thanks for reporting.

Also, I just (a few minutes ago) fixed the `intersperse` warning.

**Comment by marcbowes** [comment]
The unreachable code is the one waiting for the result of the `CREATE TABLE` to come back. It's expecting either a result or an error back, instead the channel is closing due to a crash of the transaction coroutine.

The underlying driver is retrying infinitely without backoff to get a session on a ledger that doesn't exist. Eventually that gets throttled and the transaction coroutine crashes due to not being able to proceed without a session.

I think there are several issues here:

1. The session acquisition code needs to handle invalid ledger names
2. and not retry infinitely without backoff
3. even if something goes wrong, the transaction coroutine should expose the error before crashing

**Comment by marcbowes** [comment]
https://github.com/djc/bb8/issues/102

**Comment by marcbowes** [comment]
The new behavior is:

1. if you open the shell with a ledger you cannot connect to
2. it hangs 10s
3. then prints the error
4. then quits

Not *ideal*, but I think it's good enough to close this issue. What do you think, @justing-bq ?

**Comment by justing-bq** [comment]
Good enough solution to satisfy me.
Thanks.
